schema_version: 1

context:
  name: django-typer
  version: "3.6.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_typer-${{ version }}.tar.gz
  sha256: 160a78a88c28863a33c748bc094e500bbc171f6ffa663957be5efa9c646e45be

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - django >=4.2,<6.1
    - click >=8.1.8,<8.4
    - typer >=0.23.1,<0.25.0
    - typing_extensions >=3.7.4.3

tests:
  - python:
      imports:
        - django_typer
      pip_check: true
      python_version: ${{ python_min }}.*


about:
  homepage: https://github.com/django-commons/django-typer
  summary: Use Typer to define the CLI for your Django management commands.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
